# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('imagem', models.ImageField(upload_to='robo/imagens', verbose_name='Imagem')),
                ('preco', models.DecimalField(decimal_places=6, max_digits=6, verbose_name='Preco')),
                ('descricao', models.CharField(max_length=512, verbose_name='Descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Robo',
                'verbose_name_plural': 'Robos',
                'ordering': ['nome'],
            },
        ),
    ]
