# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboComprado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.IntegerField(blank=True, choices=[(2, 'Cancelado'), (0, 'Pendente'), (1, 'Aprovado')], default=0, verbose_name='Situacao')),
                ('name_mt5', models.CharField(max_length=50, verbose_name='Nome MT5')),
            ],
        ),
        migrations.AlterField(
            model_name='robo',
            name='imagem',
            field=models.ImageField(upload_to='mammontrading/imagens', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='robocomprado',
            name='robo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='robo.Robo', verbose_name='Robo'),
        ),
        migrations.AddField(
            model_name='robocomprado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
