# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0003_auto_20170728_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robo',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preco'),
        ),
        migrations.AlterField(
            model_name='robocomprado',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Cancelado'), (0, 'Pendente'), (1, 'Aprovado')], default=0, verbose_name='Situacao'),
        ),
    ]
