# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0005_auto_20170728_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='robocomprado',
            name='codigo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos'),
        ),
        migrations.AlterField(
            model_name='robocomprado',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprovado'), (0, 'Pendente'), (2, 'Cancelado')], default=0, verbose_name='Situacao'),
        ),
    ]
