# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0006_auto_20170728_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robocomprado',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Cancelado'), (0, 'Pendente'), (1, 'Aprovado')], default=0, verbose_name='Situacao'),
        ),
    ]
