# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0008_auto_20170913_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robocomprado',
            name='tipo',
        ),
        migrations.AddField(
            model_name='robo',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Moderado'), (2, 'Arrojado'), (0, 'Conservador')], default=0, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='robocomprado',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Cancelado'), (1, 'Aprovado'), (0, 'Pendente')], default=0, verbose_name='Situacao'),
        ),
    ]
