# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Slug')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('endereco_original', models.CharField(max_length=255, verbose_name='Link')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Slug')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('endereco', models.CharField(max_length=255, verbose_name='Link')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
