# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0002_auto_20170728_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens', verbose_name='Imagem'),
        ),
    ]
