# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:32
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0003_artigo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=tinymce.models.HTMLField(verbose_name='Texto'),
        ),
    ]
